// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import GoogleMap__ApplicationController from "./google_map/application_controller"
application.register("google-map--application", GoogleMap__ApplicationController)

import GoogleMap__IndexController from "./google_map/index_controller"
application.register("google-map--index", GoogleMap__IndexController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)
