FROM ruby:3.2.3
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

RUN apt-get update -qq \
    && apt-get install -y ca-certificates curl gnupg \
    && mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && NODE_MAJOR=20 \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -qq \
    && apt-get install -y \
    wget \
    build-essential \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libgif-dev \
    libwebp-dev \
    libopenexr-dev \
    libheif-dev \
    libde265-dev \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://imagemagick.org/download/releases/ImageMagick-7.1.1-32.tar.gz \
    && tar -xzf ImageMagick-7.1.1-32.tar.gz \
    && cd ImageMagick-7.1.1-32 \
    && ./configure \
    && make \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf ImageMagick-7.1.1-32 \
    && rm ImageMagick-7.1.1-32.tar.gz

RUN mkdir /myapp
WORKDIR /myapp
RUN gem install bundler
COPY . /myapp